version: "3.8"
services: 
  web: 
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: php74
    depends_on:
      - database
    ports: 
      - "80:80"
    volumes: 
      - "./php:/var/www/html"
  database: 
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: mysql8
    environment: 
      MYSQL_DATABASE: defaultdb
      MYSQL_ROOT_PASSWORD: "rootPass"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbuserpassword"
    image: "mysql:8.0.21"
    ports: 
      - "6033:3306"
    restart: always

