version: "3.8"
services: 
  web: 
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: php74
    depends_on:
      - database
    ports: 
      - "80:80"
    volumes: 
      - "./php:/var/www/html"
  database: 
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: mysql8
    environment: 
      MYSQL_DATABASE: quizzane
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "quizzane"
      MYSQL_PASSWORD: "QFtdFZk2wC-c4skfJ?5#TPLrXyeZVTJ99=s*GEBVR_!XQ9B?_?NE+Dwc7pL!2fzb"
    image: "mysql:8.0.21"
    ports: 
      - "6033:3306"
    restart: always
