name: 'ShellCheck'
on:
  - pull_request
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC2164 SC2162 SC2016 SC1090 # It is posible to exclude some shellcheck warnings.
        with:
          sh_checker_comment: true
          sh_checker_shfmt_disable: true
